// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('login-test', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').usingServer('http://localhost:4444/wd/hub').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('login-test', async function() {
    await driver.get("https://opensource-demo.orangehrmlive.com/index.php/auth/login")
    await driver.manage().window().setRect(1366, 728)
    await driver.findElement(By.id("txtUsername")).click()
    await driver.findElement(By.id("txtUsername")).sendKeys("Admin")
    await driver.findElement(By.id("txtPassword")).click()
    await driver.findElement(By.id("txtPassword")).sendKeys("admin123")
    await driver.findElement(By.id("btnLogin")).click()
  })
})
